# Generated by Django 5.0.3 on 2024-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
