# Generated by Django 5.0.3 on 2024-04-23 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_addressess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('Sargodha', 'Sargodha'), ('Kot Momin', 'Kot Momin'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Faislabad', 'Faislabad'), ('Lahore', 'Lahore')], max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Addressess',
        ),
    ]
