# Generated by Django 5.0.3 on 2024-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_addresses_delete_addressess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('E', 'Electronics'), ('B', 'Books'), ('C', 'Clothing'), ('AC', 'Accessories')], max_length=2),
        ),
    ]
