# Generated by Django 5.0.4 on 2024-05-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cart_items_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
    ]
