# Generated by Django 5.0.4 on 2024-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_orderplaced_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Sargodha', 'Sargodha'), ('Kot Momin', 'Kot Momin'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Faislabad', 'Faislabad'), ('Lahore', 'Lahore')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
