# Generated by Django 5.0.4 on 2024-05-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('On The Way', 'On The Way'), ('Received', 'Received'), ('Paid', 'Paid')], default='Pending', max_length=200),
        ),
    ]
