# Generated by Django 5.0.4 on 2024-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
